language: c++

os:
  - linux
  - osx

env:
  matrix:
      - BUILD_TYPE=Debug
      - BUILD_TYPE=Release

compiler:
  - gcc
  - clang

script:
  - mkdir build ; cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=../install || true
  - cmake --build . --config $BUILD_TYPE
  - cmake --build . --target install

after_success:
  - ./examples/01-simple_controller ../examples/resources/lwr.urdf
