language: c++

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew update && brew install gcc@5 && brew link --overwrite gcc@5 && CC=gcc && CXX=g++"

    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew update && brew install gcc@6 && brew link --overwrite gcc@6 && CC=gcc && CXX=g++"

    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew update && brew install gcc && brew link --overwrite gcc && CC=gcc && CXX=g++"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir -p $HOME/orca-install
  - mkdir build ; cd build
  - cmake .. -DCMAKE_CXX_FLAGS="-w" -DCMAKE_INSTALL_PREFIX=$HOME/orca-install
  - cmake --build . --config Release
  - cmake --build . --target install

after_success:
  - ./examples/01-simple_controller ../examples/resources/lwr.urdf
