version: 2.0.{build}

clone_folder: c:\projects\orca

os:
 - Visual Studio 2015
 - Visual Studio 2017

install:

build:

build_script:
  # compile orca
  - cd c:\projects\orca
  - md build
  - cd build
  - cmake .. || true
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" orca.sln
  - cmake --build . --config Release
  - ctest --output-on-failure --build-config Release
  - cmake --build . --config Release --target INSTALL
