package:
  name: osqp
  version: "0.3.0"

source:
  git_url: https://github.com/oxfordcontrol/osqp.git
  git_tag: v0.3.0


# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - scs = scs:main
    #
    # Would create an entry point called scs that calls scs.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - future
    - numpy >=1.7
    - scipy >=0.13.2

  run:
    - python
    - future
    - numpy >=1.7
    - scipy >=0.13.2

test:
  # Python imports
  imports:
    - osqp

about:
  home: http://osqp.readthedocs.io/
  license: Apache 2.0
  license_file: LICENSE
  summary: 'OSQP: The Operator Splitting QP Solver'
